# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-30, 20, 771, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.Products = QtWidgets.QWidget()
        self.Products.setMouseTracking(True)
        self.Products.setTabletTracking(True)
        self.Products.setAutoFillBackground(False)
        self.Products.setObjectName("Products")
        self.tableView = QtWidgets.QTableView(self.Products)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 381, 451))
        self.tableView.setObjectName("tableView")
        self.pushButton_2 = QtWidgets.QPushButton(self.Products)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 10, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Products)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 10, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Products)
        self.pushButton_4.setGeometry(QtCore.QRect(590, 140, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.Products)
        self.label.setGeometry(QtCore.QRect(440, 50, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.Products)
        self.lineEdit.setGeometry(QtCore.QRect(550, 50, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Products)
        self.label_2.setGeometry(QtCore.QRect(440, 80, 60, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_2.setGeometry(QtCore.QRect(550, 80, 151, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.Products)
        self.label_3.setGeometry(QtCore.QRect(440, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_3.setGeometry(QtCore.QRect(550, 110, 151, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.Products, "")
        self.Peers = QtWidgets.QWidget()
        self.Peers.setObjectName("Peers")
        self.listView = QtWidgets.QListView(self.Peers)
        self.listView.setGeometry(QtCore.QRect(0, 0, 301, 471))
        self.listView.setObjectName("listView")
        
        self.pushButton = QtWidgets.QPushButton(self.Peers)
        self.pushButton.setGeometry(QtCore.QRect(310, 10, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Peers, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PeerToPeerShoping"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_4.setText(_translate("MainWindow", "Save/Add"))
        self.label.setText(_translate("MainWindow", "Product Name"))
        self.label_2.setText(_translate("MainWindow", "Amount"))
        self.label_3.setText(_translate("MainWindow", "Unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Products), _translate("MainWindow", "Products"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Peers), _translate("MainWindow", "Peers"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
    