# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from db_operations import DataBase
from models.product import Product
from peer import Peer
from models.demand import Demand
from models.offer import Offer
from uuid import uuid4


class Ui_MainWindow(object):
    def __init__(self, peer: Peer):
        super().__init__()
        self.peer = peer
        self.selected_product_line = -1

        peer.on_change_callbacks.append(self.init_peers_data)
        peer.on_change_callbacks.append(self.init_data)

        peer.on_change_callbacks.append(self.init_demand_data)
        peer.on_change_callbacks.append(self.init_offer_data)

        self.db = DataBase()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(9200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 771, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.Products = QtWidgets.QWidget()
        self.Products.setMouseTracking(True)
        self.Products.setTabletTracking(True)
        self.Products.setAutoFillBackground(False)
        self.Products.setObjectName("Products")

        self.Offer = QtWidgets.QWidget()
        self.Offer.setMouseTracking(True)
        self.Offer.setTabletTracking(True)
        self.Offer.setAutoFillBackground(False)
        self.Offer.setObjectName("Offer")

        self.Demand = QtWidgets.QWidget()
        self.Demand.setMouseTracking(True)
        self.Demand.setTabletTracking(True)
        self.Demand.setAutoFillBackground(False)
        self.Demand.setObjectName("Demand")

        # Product Tab
        self.tableView: QtWidgets.QTableView = QtWidgets.QTableView(
            self.Products)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 381, 451))
        self.tableView.setObjectName("tableView")
        self.products_model = QtGui.QStandardItemModel()
        self.products_model.setHorizontalHeaderLabels(
            ['Name', 'Unit', 'Desc', 'Amount'])
        self.init_data()
        self.tableView.setModel(self.products_model)

        self.pushButton_2 = QtWidgets.QPushButton(self.Products)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 10, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Products)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 10, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_save_add = QtWidgets.QPushButton(self.Products)
        self.pushButton_save_add.setGeometry(QtCore.QRect(590, 140, 113, 32))
        self.pushButton_save_add.setObjectName("pushButton_save_add")
        self.pushButton_save_add.clicked.connect(self.save_edit_products)
        self.label = QtWidgets.QLabel(self.Products)
        self.label.setGeometry(QtCore.QRect(440, 50, 200, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.Products)
        self.lineEdit.setGeometry(QtCore.QRect(600, 50, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Products)
        self.label_2.setGeometry(QtCore.QRect(440, 80, 200, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_2.setGeometry(QtCore.QRect(600, 80, 151, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.Products)
        self.label_3.setGeometry(QtCore.QRect(440, 110, 200, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 110, 151, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.Products, "")

        # Peers Tabs
        self.Peers = QtWidgets.QWidget()
        self.Peers.setObjectName("Peers")

        # init peers data
        self.tableView: QtWidgets.QTableView = QtWidgets.QTableView(self.Peers)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 500, 451))
        self.tableView.setObjectName("tableView")
        self.peers_model = QtGui.QStandardItemModel()
        self.peers_model.setHorizontalHeaderLabels(
            ['Name', 'Uuid', 'Ip', 'Port', 'Desc', 'Geoloc'])
        self.init_peers_data()
        self.tableView.setModel(self.peers_model)

        self.pushButton = QtWidgets.QPushButton(self.Peers)
        self.pushButton.setGeometry(QtCore.QRect(600, 10, 113, 32))
        self.pushButton.setObjectName("pushButton")

        # Offer Tab
        self.tableView_offer: QtWidgets.QTableView = QtWidgets.QTableView(
            self.Offer)
        self.tableView_offer.setGeometry(QtCore.QRect(30, 10, 381, 451))
        self.tableView_offer.setObjectName("tableView")
        self.offer_model = QtGui.QStandardItemModel()
        self.offer_model.setHorizontalHeaderLabels(
            ['Offer Uuid', 'Offer Name,', 'Offered Product Name', 'Offered Product Amount',  'Exchange Product Name', 'Exchange Product Amount'])
        self.init_offer_data()
        self.tableView_offer.setModel(self.offer_model)

        self.pushButton_2_offer = QtWidgets.QPushButton(self.Offer)
        self.pushButton_2_offer.setGeometry(QtCore.QRect(430, 10, 113, 32))
        self.pushButton_2_offer.setObjectName("pushButton_2")
        self.pushButton_3_offer = QtWidgets.QPushButton(self.Offer)
        self.pushButton_3_offer.setGeometry(QtCore.QRect(600, 10, 113, 32))
        self.pushButton_3_offer.setObjectName("pushButton_3")
        self.pushButton_save_add_offer = QtWidgets.QPushButton(self.Offer)
        self.pushButton_save_add_offer.setGeometry(
            QtCore.QRect(590, 230, 113, 32))
        self.pushButton_save_add_offer.setObjectName("pushButton_save_add")
        self.pushButton_save_add_offer.clicked.connect(self.save_edit_offer)

        self.label_offer = QtWidgets.QLabel(self.Offer)
        self.label_offer.setGeometry(QtCore.QRect(440, 50, 200, 16))
        self.label_offer.setObjectName("label")
        self.lineEdit_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_offer.setGeometry(QtCore.QRect(600, 50, 151, 21))
        self.lineEdit_offer.setObjectName("lineEdit")

        self.label_2_offer = QtWidgets.QLabel(self.Offer)
        self.label_2_offer.setGeometry(QtCore.QRect(440, 80, 200, 16))
        self.label_2_offer.setObjectName("label_2")
        self.lineEdit_2_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_2_offer.setGeometry(QtCore.QRect(600, 80, 151, 21))
        self.lineEdit_2_offer.setObjectName("lineEdit_2")

        self.label_3_offer = QtWidgets.QLabel(self.Offer)
        self.label_3_offer.setGeometry(QtCore.QRect(440, 110, 200, 16))
        self.label_3_offer.setObjectName("label_3")
        self.lineEdit_3_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_3_offer.setGeometry(QtCore.QRect(600, 110, 151, 21))
        self.lineEdit_3_offer.setObjectName("lineEdit_3")

        self.label_4_offer = QtWidgets.QLabel(self.Offer)
        self.label_4_offer.setGeometry(QtCore.QRect(440, 140, 200, 16))
        self.label_4_offer.setObjectName("label_4")
        self.lineEdit_4_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_4_offer.setGeometry(QtCore.QRect(600, 140, 151, 21))
        self.lineEdit_4_offer.setObjectName("lineEdit_4")

        self.label_5_offer = QtWidgets.QLabel(self.Offer)
        self.label_5_offer.setGeometry(QtCore.QRect(440, 170, 200, 16))
        self.label_5_offer.setObjectName("label_5")
        self.lineEdit_5_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_5_offer.setGeometry(QtCore.QRect(600, 170, 151, 21))
        self.lineEdit_5_offer.setObjectName("lineEdit_5")

        self.label_6_offer = QtWidgets.QLabel(self.Offer)
        self.label_6_offer.setGeometry(QtCore.QRect(440, 200, 200, 16))
        self.label_6_offer.setObjectName("label_6")
        self.lineEdit_6_offer = QtWidgets.QLineEdit(self.Offer)
        self.lineEdit_6_offer.setGeometry(QtCore.QRect(600, 200, 151, 21))
        self.lineEdit_6_offer.setObjectName("lineEdit_6")

        self.tabWidget.addTab(self.Offer, "")

        # demand Tab
        self.tableView_demand: QtWidgets.QTableView = QtWidgets.QTableView(
            self.Demand)
        self.tableView_demand.setGeometry(QtCore.QRect(30, 10, 381, 451))
        self.tableView_demand.setObjectName("tableView")
        self.demand_model = QtGui.QStandardItemModel()
        self.demand_model.setHorizontalHeaderLabels(
            ['Demand Uuid', 'Demand Name', 'Requested Product Name', 'Requested Product Amount',  'Exchange Product Name', 'Exchange Product Amount'])
        self.tableView_demand.setModel(self.demand_model)
        self.init_demand_data()
        self.pushButton_2_demand = QtWidgets.QPushButton(self.Demand)
        self.pushButton_2_demand.setGeometry(QtCore.QRect(430, 10, 113, 32))
        self.pushButton_2_demand.setObjectName("pushButton_2")
        self.pushButton_3_demand = QtWidgets.QPushButton(self.Demand)
        self.pushButton_3_demand.setGeometry(QtCore.QRect(600, 10, 113, 32))
        self.pushButton_3_demand.setObjectName("pushButton_3")
        self.pushButton_save_add_demand = QtWidgets.QPushButton(self.Demand)
        self.pushButton_save_add_demand.setGeometry(
            QtCore.QRect(590, 230, 113, 32))
        self.pushButton_save_add_demand.setObjectName("pushButton_save_add")
        self.pushButton_save_add_demand.clicked.connect(self.save_edit_demand)
        self.label_demand = QtWidgets.QLabel(self.Demand)
        self.label_demand.setGeometry(QtCore.QRect(440, 50, 200, 16))
        self.label_demand.setObjectName("label")
        self.lineEdit_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_demand.setGeometry(QtCore.QRect(600, 50, 151, 21))
        self.lineEdit_demand.setObjectName("lineEdit")
        self.label_2_demand = QtWidgets.QLabel(self.Demand)
        self.label_2_demand.setGeometry(QtCore.QRect(440, 80, 200, 16))
        self.label_2_demand.setObjectName("label_2")
        self.lineEdit_2_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_2_demand.setGeometry(QtCore.QRect(600, 80, 151, 21))
        self.lineEdit_2_demand.setObjectName("lineEdit_2")
        self.label_3_demand = QtWidgets.QLabel(self.Demand)
        self.label_3_demand.setGeometry(QtCore.QRect(440, 110, 200, 16))
        self.label_3_demand.setObjectName("label_3")
        self.lineEdit_3_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_3_demand.setGeometry(QtCore.QRect(600, 110, 151, 21))
        self.lineEdit_3_demand.setObjectName("lineEdit_3")
        self.label_4_demand = QtWidgets.QLabel(self.Demand)
        self.label_4_demand.setGeometry(QtCore.QRect(440, 140, 200, 16))
        self.label_4_demand.setObjectName("label_4")
        self.lineEdit_4_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_4_demand.setGeometry(QtCore.QRect(600, 140, 151, 21))
        self.lineEdit_4_demand.setObjectName("lineEdit_4")

        self.label_5_demand = QtWidgets.QLabel(self.Demand)
        self.label_5_demand.setGeometry(QtCore.QRect(440, 170, 200, 16))
        self.label_5_demand.setObjectName("label_5")
        self.lineEdit_5_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_5_demand.setGeometry(QtCore.QRect(600, 170, 151, 21))
        self.lineEdit_5_demand.setObjectName("lineEdit_5")

        self.label_6_demand = QtWidgets.QLabel(self.Demand)
        self.label_6_demand.setGeometry(QtCore.QRect(440, 200, 200, 16))
        self.label_6_demand.setObjectName("label_6")
        self.lineEdit_6_demand = QtWidgets.QLineEdit(self.Demand)
        self.lineEdit_6_demand.setGeometry(QtCore.QRect(600, 200, 151, 21))
        self.lineEdit_6_demand.setObjectName("lineEdit_6")

        self.tabWidget.addTab(self.Demand, "")

        self.tabWidget.addTab(self.Peers, "")
        self.tabWidget.addTab(self.Offer, "")
        self.tabWidget.addTab(self.Demand, "")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "PeerToPeerShoping"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_save_add.setText(_translate("MainWindow", "Save/Add"))
        self.label.setText(_translate("MainWindow", "Product Name"))
        self.label_2.setText(_translate("MainWindow", "Amount"))
        self.label_3.setText(_translate("MainWindow", "Unit"))

        self.pushButton_2_demand.setText(_translate("MainWindow", "Edit"))
        self.pushButton_3_demand.setText(_translate("MainWindow", "Delete"))
        self.pushButton_save_add_demand.setText(
            _translate("MainWindow", "Save/Add"))
        self.label_demand.setText(_translate(
            "MainWindow", "Requested Product Name"))
        self.label_2_demand.setText(_translate(
            "MainWindow", "Requested Product Amount"))
        self.label_3_demand.setText(_translate(
            "MainWindow", "Requested Product Unit"))
        self.label_4_demand.setText(_translate(
            "MainWindow", "Exchanged Product Name"))
        self.label_5_demand.setText(_translate(
            "MainWindow", "Exchanged Product Amount"))
        self.label_6_demand.setText(_translate(
            "MainWindow", "Exchanged Product Unit"))

        self.pushButton_2_offer.setText(_translate("MainWindow", "Edit"))
        self.pushButton_3_offer.setText(_translate("MainWindow", "Delete"))
        self.pushButton_save_add_offer.setText(
            _translate("MainWindow", "Save/Add"))
        self.label_offer.setText(_translate(
            "MainWindow", "Offered Product Name"))
        self.label_2_offer.setText(_translate(
            "MainWindow", "Offered Product Amount"))
        self.label_3_offer.setText(_translate(
            "MainWindow", "Offered Product Unit"))
        self.label_4_offer.setText(_translate(
            "MainWindow", "Exchanged Product Name"))
        self.label_5_offer.setText(_translate(
            "MainWindow", "Exchanged Product Amount"))
        self.label_6_offer.setText(_translate(
            "MainWindow", "Exchanged Product Unit"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Products), _translate("MainWindow", "Products"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Peers), _translate("MainWindow", "Peers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Offer), _translate("MainWindow", "Offer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.Demand), _translate("MainWindow", "Demand"))

        self.pushButton.setText(_translate("MainWindow", "Delete"))

    def init_data(self):
        print("init data")
        try:
            data = self.db.read_products_as_list()
        except Exception as e:
            print(e)
            print("hata")
            return
        for i, row in enumerate(data):
            print(row)
            for j, col in enumerate(row):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(data[i][j]))
                self.products_model.setItem(i, j, item)

    def init_peers_data(self):
        for i, peer_info in enumerate(self.peer.get_peers()):
            peer_info_data_list = [
                peer_info.keywords,
                peer_info.uuid,
                peer_info.ip,
                peer_info.port,
            ]
            for j, col in enumerate(peer_info_data_list):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(col))
                self.peers_model.setItem(i, j, item)

    def save_edit_products(self):
        p = Product(
            name=self.lineEdit.text(),
            unit_key=self.lineEdit_3.text(),
            amount=self.lineEdit_2.text()
        )
        print(p.name, p.unit_key, p.amount)
        self.db.save_edit_products(
            p
        )
        self.init_data()

    def init_demand_data(self):
        for i, d in enumerate(self.peer.demands):
            for j, val in enumerate(d.to_list()):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(val))
                self.demand_model.setItem(i, j, item)

    def init_offer_data(self):
        for i, d in enumerate(self.peer.offers):
            for j, val in enumerate(d.to_list()):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(val))
                self.offer_model.setItem(i, j, item)

    def save_edit_offer(self):
        offered_p = Product(
            name=self.lineEdit_offer.text(),
            unit_key=self.lineEdit_3_offer.text(),
            amount=self.lineEdit_2_offer.text()
        )
        print(offered_p.amount,offered_p.unit_key)

        exchange_p = Product(
            name=self.lineEdit_4_offer.text(),
            unit_key=self.lineEdit_6_offer.text(),
            amount=self.lineEdit_5_offer.text()
        )
        print(exchange_p.amount,exchange_p.unit_key)
        name = offered_p.name + " offered aginst " + exchange_p.name
        self.peer.create_offer(name=name,offered_product=offered_p,exchange_product=exchange_p)

    def save_edit_demand(self):
        requested_product = Product(
            name=self.lineEdit_demand.text(),
            unit_key=self.lineEdit_3_demand.text(),
            amount=self.lineEdit_2_demand.text()
        )

        exchange_p = Product(
            name=self.lineEdit_4_demand.text(),
            unit_key=self.lineEdit_6_demand.text(),
            amount=self.lineEdit_5_demand.text()
        )
        name = requested_product.name + " demanded aginst " + exchange_p.name
        self.peer.create_demand(name=name,requested_product=requested_product,exchange_product=exchange_p)


class TableModel(QtCore.QAbstractTableModel):
    def __init__(self, data):
        super(TableModel, self).__init__()
        self._data = data

    def data(self, index, role):
        if role == QtCore.Qt.DisplayRole:
            # See below for the nested-list data structure.
            # .row() indexes into the outer list,
            # .column() indexes into the sub-list
            return self._data[index.row()][index.column()]

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])
