# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'psp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from db_operations import DataBase
from models.product import Product
from peer import Peer


class Ui_MainWindow(object):
    def __init__(self,peer:Peer):
        super().__init__()
        self.peer = peer
        self.selected_product_line = -1

        peer.on_change_callbacks.append(self.init_peers_data)
        peer.on_change_callbacks.append(self.init_data)
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-30, 20, 771, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.Products = QtWidgets.QWidget()
        self.Products.setMouseTracking(True)
        self.Products.setTabletTracking(True)
        self.Products.setAutoFillBackground(False)
        self.Products.setObjectName("Products")
        
        self.tableView:QtWidgets.QTableView = QtWidgets.QTableView(self.Products)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 381, 451))
        self.tableView.setObjectName("tableView")
        self.products_model = QtGui.QStandardItemModel()
        self.products_model.setHorizontalHeaderLabels(['Name', 'Unit', 'Desc', 'Amount'])

                
        self.init_data()
        self.tableView.setModel(self.products_model)
      
        #self.tableView.
        self.pushButton_2 = QtWidgets.QPushButton(self.Products)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 10, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Products)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 10, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_save_add = QtWidgets.QPushButton(self.Products)
        self.pushButton_save_add.setGeometry(QtCore.QRect(590, 140, 113, 32))
        self.pushButton_save_add.setObjectName("pushButton_save_add")
       
        self.pushButton_save_add.clicked.connect(self.save_edit_products)
        
        self.label = QtWidgets.QLabel(self.Products)
        self.label.setGeometry(QtCore.QRect(440, 50, 91, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.Products)
        self.lineEdit.setGeometry(QtCore.QRect(550, 50, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.Products)
        self.label_2.setGeometry(QtCore.QRect(440, 80, 60, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_2.setGeometry(QtCore.QRect(550, 80, 151, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.Products)
        self.label_3.setGeometry(QtCore.QRect(440, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Products)
        self.lineEdit_3.setGeometry(QtCore.QRect(550, 110, 151, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget.addTab(self.Products, "")
        self.Peers = QtWidgets.QWidget()
        self.Peers.setObjectName("Peers")

        # init peers data
        self.tableView:QtWidgets.QTableView = QtWidgets.QTableView(self.Peers)
        self.tableView.setGeometry(QtCore.QRect(30, 10, 500, 451))
        self.tableView.setObjectName("tableView")
        self.peers_model = QtGui.QStandardItemModel()
        self.peers_model.setHorizontalHeaderLabels(['Name', 'Uuid','Ip','Port','Desc', 'Geoloc'])
        self.init_peers_data()
        self.tableView.setModel(self.peers_model)
        
        self.pushButton = QtWidgets.QPushButton(self.Peers)
        self.pushButton.setGeometry(QtCore.QRect(550, 10, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Peers, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PeerToPeerShoping"))
        self.pushButton_2.setText(_translate("MainWindow", "Edit"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_save_add.setText(_translate("MainWindow", "Save/Add"))
        self.label.setText(_translate("MainWindow", "Product Name"))
        self.label_2.setText(_translate("MainWindow", "Amount"))
        self.label_3.setText(_translate("MainWindow", "Unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Products), _translate("MainWindow", "Products"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Peers), _translate("MainWindow", "Peers"))
        self.pushButton.setText(_translate("MainWindow", "Delete"))
    
    def init_data(self):
        db = DataBase()
        data = db.read_products_as_list()
        for i,row in enumerate(data):
            for j,col in enumerate(row):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(data[i][j]))
                self.products_model.setItem(i,j,item)
 
    def init_peers_data(self):
        for i, peer_info in enumerate(self.peer.get_peers()):
            peer_info_data_list = [
                peer_info.keywords,
                peer_info.uuid,
                peer_info.ip,
                peer_info.port,
            ]
            for j, col in enumerate(peer_info_data_list):
                item = QtGui.QStandardItem()
                item.setToolTip(str(i))
                item.setText(str(col))
                self.peers_model.setItem(i,j,item)   
                    
    def save_edit_products(self):
        db = DataBase()
        db.save_edit_products(
            Product(
                name=self.lineEdit.text(),
                unit_key=self.lineEdit_2.text(),
                amount= self.lineEdit_3.text()
            )
        )
        self.init_data()
        
class TableModel(QtCore.QAbstractTableModel):
    def __init__(self, data):
        super(TableModel, self).__init__()
        self._data = data

    def data(self, index, role):
        if role == QtCore.Qt.DisplayRole:
            # See below for the nested-list data structure.
            # .row() indexes into the outer list,
            # .column() indexes into the sub-list
            return self._data[index.row()][index.column()]

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])
